CREATE SEQUENCE monster_id_seq
START WITH 100;

CREATE SEQUENCE area_id_seq
START WITH 1;

CREATE SEQUENCE weapon_id_seq
START WITH 1000;

CREATE SEQUENCE armor_id_seq
START WITH 2000;

CREATE SEQUENCE hunter_id_seq
START WITH 20000;
