CREATE SEQUENCE monster_history_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE area_history_seq START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE hunter_weapon_history_seq START WITH 2001 INCREMENT BY 1;
CREATE SEQUENCE hunter_armor_history_seq START WITH 3001 INCREMENT BY 1;
CREATE SEQUENCE hunter_history_seq START WITH 4001 INCREMENT BY 1;
